version: '3.8'

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server_service
    depends_on:
      - postgres
    ports:
      - "3000:3000"
    restart: always
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: client_service
    depends_on:
      - server
    ports:
      - "5173:5173"
    networks:
      - app-network

  postgres:
    image: postgres:16.2
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: app-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx_proxy
    depends_on:
      - client
    ports:
      - "80:80"
    networks:
      - app-network

volumes:
  postgres_data:

networks:
  app-network:
